workflows:
  android-debug-build:
    name: Android Debug APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: latest
      java: 17
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          
      - name: Build Web App
        script: |
          npm run build
          
      - name: Sync Capacitor
        script: |
          npx cap add android || true
          npx cap sync android
          
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk