workflows:
  android-apk:
    name: SiteBoss Android APK
    max_build_duration: 60

    environment:
      node: 22
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Verify Android platform
        script: |
          if [ ! -d "android" ]; then
            echo "❌ Android platform missing. Run 'npx cap add android' locally and push it."
            exit 1
          fi

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build Debug APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - sahilmeshram1917@gmail.com
        notify:
          success: true
          failure: true
